language: ruby
rvm:
- 2.5
- 2.6
- 2.7
- 3.0
script:
- bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: OUlCntNtWloKunpBLvEIgrNthLtVl04uk7VD76kx8h+xXorjJCWaU3KKfi2MSyEtWB/fgUrAnEbzETfCt154Hq8TyKyMQqixAgDVTvXt84fB0IjKcszhtv3yUNGb+l1LWdEVkdzcRyf/yTZE3rPJi5VHqHe++G6hehmm417sPS/Wo+xEJ+2EVq/KX0aMahtrhqvuYJCSv/L25e3ExAHx27u8Q3w5vUQW3cy/FcyYUxGWL6JIWHMcI9fGu417AQd9nHOOys6DsLl+/7yMblbPNz0UyBaKqioEv+EFWpcvV8qKRi81s4sAbzJwF5DcOxYvtumrNJWi2slRiDmUx7q821hscsRlfMfYARMVLm0CuFhg9q7ldagOdCdD/reE88ofqStVVjDNj7u3zwBeeuwtKY6frGO2fR81pec/JYA8LlKEeVjFv/HZL4qJ5vgf/BSX4EQ6vEmL0gTXvS3CBFEL36h1PPSnzrwB7ktiCG8typ0CVrYPjDqm1naneraXm2dCVw2wAXLqOdJGq9pAFnKnwi3b+twTE9px5ttEkoEIZ2ASEK4L1edK508Uh90127kokfCKmv0wCSr3zr4F3tQy0pRiNuDUvZaF9QwE4uzzp2HYHvptT5OkcA1B9TQ9x9dsdQe+4siTkcF0Rz/LWmlrmVrExYhxptyeS6yP7rLotiM=
  gem: gumball
  on:
    tags: true
    repo: kevinstuffandthings/gumball
  skip_cleanup: 'true'
